name: Check for IANA Database updates

# Triggers every midnight UTC
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  outdated:
    name: Check for IANA Database updates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: .github/workflows/update-iana-db-version.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
